version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout
      - run: maven clean install
  test:
    docker:
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout
      - run: maven test
  deploy:
    docker:
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout
      - run: maven deploy --settings .circleci/settings.xml -DskipTests -Dcheckstyle.skip -B Prelease

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test