name: "Deploy on Merge"

on:
  push:
    branches: [ master ]

jobs:
  merge_deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "16"
        env:
          LIELS_REPO_PASSWORD: ${{ secrets.LIELS_REPO_PASSWORD }}
          LIELS_REPO_USERNAME: ${{ secrets.LIELS_REPO_USERNAME }}

      - name: Deploy
        run: mvn deploy --settings .github/settings.xml