name: Pull Requests Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_requests:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
#          settings-path: ${{ github.workspace }}

      - name: Clean & Install
        run: mvn clean install

      - name: Test
        run: mvn test

      - name: Package
        run: mvn package